# Generated by Django 4.2.7 on 2023-11-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
                ('Alternate_no', models.IntegerField(unique=True)),
                ('GST_no', models.CharField(max_length=150, unique=True)),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('amc_client', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
