# Generated by Django 4.2.7 on 2023-11-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clients_delete_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Alternate_no',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
