# Generated by Django 4.2.7 on 2023-11-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clients_alternate_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='amc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='amc_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
