# Generated by Django 4.2.7 on 2023-12-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
    ]
