# Generated by Django 4.2.7 on 2023-12-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_serialnumber_product_serial_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serial_numbers',
        ),
        migrations.DeleteModel(
            name='SerialNumber',
        ),
        migrations.AddField(
            model_name='product',
            name='serial_numbers',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
