# Generated by Django 4.2.7 on 2023-12-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_serial_numbers_delete_serialnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serial_numbers',
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('S', 'Sold'), ('NS', 'Not Sold')], default='NS', max_length=2)),
                ('in_date', models.DateField()),
                ('update_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialnumber', to='inventory.product')),
            ],
        ),
    ]
