# Generated by Django 4.2.7 on 2023-12-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_serial_numbers_serialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='in_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='update_date',
            field=models.DateField(blank=True),
        ),
    ]
